### ISSUE TITLE
Totally freezes the tab

### ISSUE THREAD

**Issue by tonysamperi** [thisissoon/angular-ellipsis#10]
As soon as I enter a component with `snEllipsis` the application freezes.
The Chrome task manager CPU raises over 130.

Env:
- Asus ROG 2015 (i7 6700 HQ + GTX960M + 16GB RAM DDR4)
- Chrome 65.0.3325.181 x64

<pre><code>
@angular/cdk: 5.2.4
@angular/cli: 1.6.3
@angular/flex-layout: 2.0.0-beta.10-4905443
@angular/material: 5.2.4
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.4.8
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.17
typescript: 2.4.2
webpack: 3.10.0**
</code></pre>

**Comment by edoparearyee** [comment]
@tonysamperi Which version of angular you are using?

Also can you include minimal steps to reproduce this issue like a [plunker](https://plnkr.co/)?

**Comment by tonysamperi** [comment]
In the previous comments are all the specs: **angular 5.2.4**

On StackBlitz it's easier to set up a demo with the same deps.

I'll do it as soon as possibile. Unfortunately I'm in a hurry right now...
So apparently my app won't be featuring the ellipsis since I don't have the time to debug it!

**Comment by andrew-aladev** [comment]
https://github.com/thisissoon/angular-ellipsis/blob/master/src/app/ellipsis/ellipsis.directive.ts

```
let text = el.innerText.split(' ');
while (this.hasOverflow) {
    text = text.slice(0, -1);
    el.innerText = `${text.join(' ')}${this.ellipsisChar}`;
}
```

Sorry. I have to insert a picture here.

![wat_png_by_katysz_by_katysz-d6j542d](https://user-images.githubusercontent.com/941925/42037079-1bb96b88-7af0-11e8-84f6-9b90e8a3ebc2.png)

We need to use binary search here.

**Comment by tonysamperi** [comment]
@andrew-aladev 
OMG.

**Comment by edoparearyee** [comment]
@andrew-aladev thank you for submitting a PR for this, we appreciate the help . However I am still unable to replicate the issue so unable to verify if it resolves it. Could you provide minimal example that replicates the issue on stackblitz or elsewhere so i can verify that the fix works. Thanks again.

**Comment by tonysamperi** [comment]
Doing it now

**Comment by tonysamperi** [comment]
I made this
https://ngx-ellipse.stackblitz.io
It doesn't freeze. But I guess angular-flex may be involved in the process of freezing..Maybe a combination of the two factors.
Anyway I solved by simply using CSS so I won't be using this plugin anymore...

**Comment by edoparearyee** [comment]
So i looked into this further found out that the issue was that the `while` loop would never end if no text would fit inside the element. I was able to replicate it and have implemented a simple fix here: https://github.com/thisissoon/angular-ellipsis/pull/12

**Comment by tonysamperi** [comment]
Interesting...good to know!!
