### ISSUE TITLE
NPM version mismatch causing build error

### ISSUE THREAD

**Issue by gs-scooter** [thisissoon/angular-ellipsis#7]
Installed latest NPM package (1.1.2) into our Angular 4 CLI project. When building, we get the following error:

`
ERROR in Error: Metadata version mismatch for module node_modules/@thisissoon/angular-ellipsis/angular-ellipsis.d.ts, found version 4, expected 3
`

The angular-ellipsis.metadata.json file does indeed contain version 4.

Could you please fix this?

**Comment by edoparearyee** [comment]
Hi @gs-scooter just tested this on a brand new cli project and cannot replicate this issue. Please try uninstalling and reinstalling the library to see if that fixes your issue by running `npm un @thisissoon/angular-ellipsis` then `npm i @thisissoon/angular-ellipsis`

**Comment by gs-scooter** [comment]
@edoparearyee - Thanks for the response.

I did a little more research and discovered this is really an Angular version compatibility issue. The lib requires Angular 5, but our project is currently on v4, which is a shame since we would need your recent dynamic content fix (i.e. can't downgrade pkg version).

**Comment by edoparearyee** [comment]
@gs-scooter I was able to replicate this for angular 4, unfortunately it appears like it's something to do with the angular 5 compiler which is unfortunate as the code itself should be compatible with 4. Will try to take a look into this soon. 

In the meantime If you are able to find a solution to get it working for 4 please submit a PR and we'll get it merged.

**Comment by edoparearyee** [comment]
Going to close this as a won't fix. Angular 5 now has LTS support as does 6 and the upgrade path from 4 to 5 or 6 is fairly straight forward.

Feel free to reopen if you feel this is still an issue
