### ISSUE TITLE
Behaviour with angular-universal

### ISSUE THREAD

**Issue by jedrichards** [thisissoon/angular-ellipsis#8]
While running on the server during universal rendering the directive raises the following error:

```
ERROR TypeError: Cannot read property 'split' of undefined
    at EllipsisDirective.clipText
```

The directive should probably be a noop on the server, and only truncate text on the client.

**Comment by edoparearyee** [comment]
@jedrichards this should be fixed now 

`npm i @thisissoon/angular-ellipsis@1.2.0`

**Comment by jedrichards** [comment]
Nice thanks!
